services:
  bus_ticket:
    container_name: buscontainer
    build: bus/
    ports:
      - "1111:80"

  flight_ticket:
    container_name: flightcontainer
    build: flight/
    ports:
      - "2222:80"
